### PR TITLE
Reintroduce methods missed from refactor

### PR DESCRIPTION
**Pull request by cescgina**
The recent refactor deleted some methods from the File class that were
used when writing the output to a file. This change also introduces
a e2e test that reproduced the issue, to avoid any future regression.

### CODE REVIEW

**Review by IgnacioPro — APPROVED** [review]
Looks good.

**Review by jsanemet — APPROVED** [review]
What worries me most is that not test show this coming.

**Comment by cescgina** [comment]
> What worries me most is that no test show this coming.

Agreed, I think the problem here was that it's only used in the orchestrator, which is very difficult to test with unit tests. I think relying on e2e tests for these cases is the best.

**Comment by jsanemet** [comment]
Fine by me.

**Pull request merged**
